"""
handover/scripts/setup.py
에이전트 프로젝트에 핸드오버 시스템을 초기화한다.

Usage:
    python setup.py --agent-id <ID> --cwd <PROJECT_PATH> [--adapter triad] [--update] [--migrate]
"""
import argparse
import json
import sys
import shutil
import os
from pathlib import Path
from datetime import datetime

SKILL_DIR = Path(__file__).parent.parent  # e.g. ~/.claude/skills/handover
TEMPLATES_DIR = SKILL_DIR / "templates"


def log_check(label: str, status: str) -> None:
    symbol = "✓" if status == "ok" else ("skip" if status == "skip" else "!")
    print(f"  [{symbol}] {label}" if status in ("ok", "skip") else f"  [!] {label}: {status}")


def load_settings(settings_path: Path) -> dict:
    if settings_path.exists():
        try:
            return json.loads(settings_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            print(f"[handover/setup] WARNING: {settings_path} is invalid JSON: {e}", file=sys.stderr)
            return {}
    return {}


def save_settings(settings_path: Path, data: dict) -> None:
    settings_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def hook_already_present(settings: dict, hook_type: str, keyword: str) -> bool:
    """Check if a hook with the given keyword already exists in the hooks section."""
    hooks_section = settings.get("hooks", {})
    # hooks can be a dict of event -> list or a list
    if isinstance(hooks_section, dict):
        for event_hooks in hooks_section.values():
            if isinstance(event_hooks, list):
                for item in event_hooks:
                    hooks = item.get("hooks", []) if isinstance(item, dict) else []
                    for h in hooks:
                        if keyword in h.get("command", ""):
                            return True
    elif isinstance(hooks_section, list):
        for item in hooks_section:
            hooks = item.get("hooks", []) if isinstance(item, dict) else []
            for h in hooks:
                if keyword in h.get("command", ""):
                    return True
    return False


def build_session_start_hook(cwd_str: str) -> dict:
    """Build the SessionStart hook entry."""
    cmd = (
        "python -c \""
        "import sys,io; sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8'); "
        f"p=r'{cwd_str}/handover_doc/CURRENT_STATE.md'; "
        "print('=== CURRENT_STATE.md ==='); "
        "print(open(p,encoding='utf-8').read()); "
        "import pathlib; "
        f"d=pathlib.Path(r'{cwd_str}/handover_doc/CURRENT_STATE.md.draft'); "
        "print('<handover-draft-pending/>') if d.exists() else None"
        "\""
    )
    return {
        "matcher": "",
        "hooks": [{"type": "command", "command": cmd, "timeout": 5}]
    }


def build_stop_hook(cwd_str: str) -> dict:
    """Build the Stop hook entry."""
    # Use forward slashes for the runner path in the command
    runner_path = cwd_str.replace("\\", "/") + "/.claude/scripts/stop_hook_runner.py"
    cmd = f"python \"{runner_path}\""
    return {
        "matcher": "",
        "hooks": [{"type": "command", "command": cmd, "timeout": 10}]
    }


def insert_hook(settings: dict, event: str, hook_entry: dict) -> None:
    """Insert a hook entry under settings['hooks'][event]."""
    if "hooks" not in settings:
        settings["hooks"] = {}
    if isinstance(settings["hooks"], list):
        # Legacy list format — convert to dict
        settings["hooks"] = {}
    if event not in settings["hooks"]:
        settings["hooks"][event] = []
    settings["hooks"][event].append(hook_entry)


def create_stop_hook_runner(cwd: Path, cwd_str: str) -> Path:
    """Create <cwd>/.claude/scripts/stop_hook_runner.py."""
    scripts_dir = cwd / ".claude" / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    runner_path = scripts_dir / "stop_hook_runner.py"
    skill_dir_str = str(SKILL_DIR).replace("\\", "/")
    content = (
        "# auto-generated by handover/scripts/setup.py\n"
        "import sys\n"
        f"sys.path.insert(0, r'{skill_dir_str}/scripts')\n"
        "from stop_hook import main\n"
        f"main(cwd=r'{cwd_str}')\n"
    )
    runner_path.write_text(content, encoding="utf-8")
    return runner_path


# 핸드오버 관련 hook 감지용 키워드
_HANDOVER_KEYWORDS = ["CURRENT_STATE.md", "stop_hook_runner.py", "handover_doc"]


def find_handover_hooks(settings: dict) -> list[tuple[str, dict]]:
    """settings 에서 핸드오버 관련 hook entry를 찾아 (event, entry) 리스트로 반환."""
    found = []
    hooks_section = settings.get("hooks", {})
    if isinstance(hooks_section, dict):
        for event, hook_list in hooks_section.items():
            if not isinstance(hook_list, list):
                continue
            for item in hook_list:
                if not isinstance(item, dict):
                    continue
                for h in item.get("hooks", []):
                    cmd = h.get("command", "")
                    if any(kw in cmd for kw in _HANDOVER_KEYWORDS):
                        found.append((event, item))
                        break
    return found


def remove_handover_hooks(settings: dict) -> int:
    """settings 에서 핸드오버 관련 hook entry를 제거. 제거된 수 반환."""
    removed = 0
    hooks_section = settings.get("hooks", {})
    if not isinstance(hooks_section, dict):
        return 0
    for event in list(hooks_section.keys()):
        hook_list = hooks_section[event]
        if not isinstance(hook_list, list):
            continue
        kept = []
        for item in hook_list:
            if not isinstance(item, dict):
                kept.append(item)
                continue
            has_handover = any(
                any(kw in h.get("command", "") for kw in _HANDOVER_KEYWORDS)
                for h in item.get("hooks", [])
            )
            if has_handover:
                removed += 1
            else:
                kept.append(item)
        hooks_section[event] = kept
    return removed


def run_migrate(cwd: Path, cwd_str: str, agent_id: str, adapter: str | None) -> bool:
    """기존 핸드오버 hook 탐지 → diff 출력 → 사용자 확인 → 제거.

    Returns:
        True  — 마이그레이션 완료 (또는 기존 hook 없음), 이후 일반 setup 진행
        False — 사용자가 취소, setup 중단
    """
    dot_claude = cwd / ".claude"
    candidates = [
        (dot_claude / "settings.json", "settings.json"),
        (dot_claude / "settings.local.json", "settings.local.json"),
    ]

    found_in: list[tuple[Path, str, dict, list[tuple[str, dict]]]] = []
    for path, name in candidates:
        s = load_settings(path)
        hits = find_handover_hooks(s)
        if hits:
            found_in.append((path, name, s, hits))

    if not found_in:
        print("[handover/migrate] 기존 핸드오버 hook 미감지 — 일반 setup으로 진행.\n")
        return True

    print("[handover/migrate] 기존 핸드오버 관련 hook 발견:\n")
    for path, name, _s, hits in found_in:
        for event, entry in hits:
            for h in entry.get("hooks", []):
                cmd = h.get("command", "")
                if any(kw in cmd for kw in _HANDOVER_KEYWORDS):
                    preview = cmd[:120] + ("..." if len(cmd) > 120 else "")
                    print(f"  [{name}] {event}:")
                    print(f"    OLD: {preview}")

    new_ss = build_session_start_hook(cwd_str)
    new_stop = build_stop_hook(cwd_str)
    new_ss_cmd = new_ss["hooks"][0]["command"]
    new_stop_cmd = new_stop["hooks"][0]["command"]
    print(f"\n  NEW SessionStart: {new_ss_cmd[:120]}...")
    print(f"  NEW Stop:         {new_stop_cmd[:80]}...")

    print()
    try:
        answer = input("기존 hook을 제거하고 새 hook으로 교체하시겠습니까? (y/N): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        answer = "n"

    if answer != "y":
        print("[handover/migrate] 취소됨. 변경 없음.")
        return False

    for path, name, s, _hits in found_in:
        n = remove_handover_hooks(s)
        save_settings(path, s)
        print(f"  ✓ [{name}] {n}개 hook 제거 완료")

    print()
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="핸드오버 시스템 초기화 — 에이전트 프로젝트에 SessionStart/Stop hook과 handover_doc/ 구성"
    )
    parser.add_argument("--agent-id", required=True, help="에이전트 식별자 (예: wesang-goon)")
    parser.add_argument("--cwd", required=True, help="프로젝트 절대경로")
    parser.add_argument("--adapter", default=None, help="어댑터 이름 (예: triad, triad-minimal)")
    parser.add_argument("--update", action="store_true", help="hook만 재등록 (CURRENT_STATE.md 보존)")
    parser.add_argument("--migrate", action="store_true", help="기존 수동 핸드오버 hook 탐지 → diff 출력 → 교체 확인")
    args = parser.parse_args()

    cwd = Path(args.cwd).resolve()
    cwd_str = str(cwd).replace("\\", "/")
    agent_id = args.agent_id
    results: list[tuple[str, str]] = []

    print(f"\n[handover/setup] agent_id={agent_id}  cwd={cwd_str}\n")

    # ------------------------------------------------------------------
    # --migrate: 기존 hook 탐지 및 교체 확인
    # ------------------------------------------------------------------
    if args.migrate:
        ok = run_migrate(cwd, cwd_str, agent_id, args.adapter)
        if not ok:
            return 0

    # ------------------------------------------------------------------
    # Step 1: Create handover_doc/
    # ------------------------------------------------------------------
    handover_doc = cwd / "handover_doc"
    if not handover_doc.exists():
        handover_doc.mkdir(parents=True, exist_ok=True)
        results.append(("handover_doc/ 생성", "ok"))
    else:
        results.append(("handover_doc/ 생성", "skip (already exists)"))

    # ------------------------------------------------------------------
    # Step 2: CURRENT_STATE.md (skip if --update)
    # ------------------------------------------------------------------
    state_file = handover_doc / "CURRENT_STATE.md"
    if args.update:
        results.append(("CURRENT_STATE.md", "skip (--update 모드)"))
    elif state_file.exists():
        results.append(("CURRENT_STATE.md", "skip (already exists)"))
    else:
        template_src = TEMPLATES_DIR / "CURRENT_STATE.md"
        if not template_src.exists():
            print(f"[handover/setup] ERROR: template not found: {template_src}", file=sys.stderr)
            return 1
        content = template_src.read_text(encoding="utf-8")
        content = content.replace("{{AGENT_NAME}}", agent_id)
        content = content.replace("{{CWD}}", cwd_str)
        state_file.write_text(content, encoding="utf-8")
        results.append(("CURRENT_STATE.md 생성", "ok"))

    # ------------------------------------------------------------------
    # Step 3: Ensure .claude/ exists
    # ------------------------------------------------------------------
    dot_claude = cwd / ".claude"
    if not dot_claude.exists():
        dot_claude.mkdir(parents=True, exist_ok=True)
        results.append((".claude/ 생성", "ok"))
    else:
        results.append((".claude/ 생성", "skip (already exists)"))

    # ------------------------------------------------------------------
    # Step 4: Read settings.json
    # ------------------------------------------------------------------
    settings_path = dot_claude / "settings.json"
    settings = load_settings(settings_path)

    # ------------------------------------------------------------------
    # Step 5: SessionStart hook
    # ------------------------------------------------------------------
    if hook_already_present(settings, "SessionStart", "CURRENT_STATE.md"):
        results.append(("SessionStart hook", "skip (already configured)"))
    else:
        hook_entry = build_session_start_hook(cwd_str)
        insert_hook(settings, "SessionStart", hook_entry)
        results.append(("SessionStart hook 등록", "ok"))

    # ------------------------------------------------------------------
    # Step 6: Stop hook + runner
    # ------------------------------------------------------------------
    if hook_already_present(settings, "Stop", "stop_hook_runner.py"):
        results.append(("Stop hook", "skip (already configured)"))
        results.append(("stop_hook_runner.py", "skip (already configured)"))
    else:
        runner_path = create_stop_hook_runner(cwd, cwd_str)
        hook_entry = build_stop_hook(cwd_str)
        insert_hook(settings, "Stop", hook_entry)
        results.append(("Stop hook 등록", "ok"))
        results.append((f"stop_hook_runner.py 생성 → {runner_path}", "ok"))

    # ------------------------------------------------------------------
    # Save settings.json
    # ------------------------------------------------------------------
    save_settings(settings_path, settings)
    results.append(("settings.json 저장", "ok"))

    # ------------------------------------------------------------------
    # Step 7: handover_config.json
    # ------------------------------------------------------------------
    config_path = dot_claude / "handover_config.json"
    config = {
        "agent_id": agent_id,
        "cwd": cwd_str,
        "adapter": args.adapter
    }
    config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")
    results.append(("handover_config.json 저장", "ok"))

    # ------------------------------------------------------------------
    # Step 8: Validate adapter if provided
    # ------------------------------------------------------------------
    if args.adapter:
        adapter_file = SKILL_DIR / "adapters" / f"{args.adapter}.json"
        if adapter_file.exists():
            results.append((f"adapter '{args.adapter}' 확인", "ok"))
        else:
            results.append((f"adapter '{args.adapter}'", f"WARNING: {adapter_file} 없음"))

    # ------------------------------------------------------------------
    # Print checklist
    # ------------------------------------------------------------------
    print("완료 체크리스트:")
    for label, status in results:
        if status == "ok":
            print(f"  ✓ {label}")
        elif status.startswith("skip"):
            print(f"  ─ {label} [{status}]")
        else:
            print(f"  ! {label} [{status}]")

    print(f"\n[handover/setup] 완료. handover_doc: {handover_doc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
